version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - '8081:80'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27018:27017'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: myDatabase
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongo_data:
